/**
This small code is just an example for using the MATLAB code [InitialCondition.m](InitialCondition.m).
This code reads the data file generated by InitialCondition.m and use the Basilisk function [distance](http://basilisk.fr/src/distance.h).
*/
#include "axi.h"
#include "fractions.h"
#include "distance.h"
#include "navier-stokes/centered.h"

scalar f[], * interfaces = {f};

int main(int argc, char const *argv[]) {
  L0 = atoi(argv[1]);

  origin (-0.11, 0.0);
  init_grid (1 << (12));
  // refine(x > -0.1 && x < 0.1 && level < 10);

  coord* InitialShape;

  char filename[80], FacetName[80];
  sprintf(filename,"f_Testing.dat");
  FILE * fp = fopen(filename,"rb");
  if ( fp == NULL ){
    fprintf(ferr, "There is no file named %s\n", filename);
    return 1;
  }
  InitialShape = input_xy(fp);
  fclose (fp);
  
  scalar d[];
  distance (d, InitialShape);

  // foreach(){
  //   fprintf(ferr, "x = %g, y = %g, d = %g\n", x, y, d[]);
  // }

  /**
  The distance function is defined at the center of each cell, we have
  to calculate the value of this function at each vertex. */
  vertex scalar phi[];
  foreach_vertex(){
    phi[] = (d[] + d[-1] + d[0,-1] + d[-1,-1])/4.;
  }
  /**
  We can now initialize the volume fraction of the domain. */
  fractions (phi, f);
  output_facets (f, ferr);
  sprintf(filename,"Init_f");
  dump (file = filename);

  sprintf(FacetName, "f_facets.dat");
  FILE * fp1 = fopen (FacetName, "w");
  output_facets (f, fp);
  fclose (fp1);
}
